'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var vue3Util = require('@ibiz-template/vue3-util');
var index = require('./auth-userinfo/index.cjs');
var index$1 = require('./nav-pos-index/index.cjs');
var index$c = require('./nav-tabs/index.cjs');
var index$d = require('./nav-breadcrumb/index.cjs');
var index$2 = require('./panel-button/index.cjs');
var index$3 = require('./panel-app-title/index.cjs');
var index$e = require('./panel-app-header/index.cjs');
var index$f = require('./panel-view-header/index.cjs');
var index$g = require('./panel-exp-header/index.cjs');
var index$h = require('./panel-view-content/index.cjs');
var index$4 = require('./panel-tab-panel/index.cjs');
var index$5 = require('./split-container/index.cjs');
var index$6 = require('./panel-index-view-search/index.cjs');
var index$i = require('./panel-app-login-view/index.cjs');
var index$j = require('./panel-remember-me/index.cjs');
var index$7 = require('./index-actions/index.cjs');
var index$l = require('./user-message/index.cjs');
var index$m = require('./searchform-buttons/index.cjs');
var index$n = require('./view-message/index.cjs');
var index$o = require('./panel-static-carousel/index.cjs');
var index$p = require('./coop-pos/index.cjs');
var index$q = require('./view-msg-pos/index.cjs');
var index$8 = require('./user-action/index.cjs');
var index$r = require('./data-import/index.cjs');
var index$s = require('./short-cut/index.cjs');
var index$t = require('./auth-captcha/index.cjs');
var index$u = require('./panel-button-list/index.cjs');
var index$b = require('./auth-sso/index.cjs');
var index$a = require('./index-blank-placeholder/index.cjs');
var index$9 = require('./global-search/index.cjs');
var index$v = require('./app-switch/index.cjs');
var index$w = require('./app-extend-menu/index.cjs');
var index$k = require('./panel-container-group/index.cjs');
var navPosIndex_state = require('./nav-pos-index/nav-pos-index.state.cjs');
var navPosIndex_controller = require('./nav-pos-index/nav-pos-index.controller.cjs');
var panelButton_controller = require('./panel-button/panel-button.controller.cjs');
var panelAppTitle_controller = require('./panel-app-title/panel-app-title.controller.cjs');
var splitContainer_controller = require('./split-container/split-container.controller.cjs');

"use strict";
const IBizPanelComponents = {
  install: (v) => {
    v.use(index$9.IBizGlobalSearch);
    v.use(index$a.IBizIndexBlankPlaceholder);
    v.use(index$b.IBizAuthSso);
    v.use(vue3Util.IBizPanelCtrlViewPageCaption);
    v.use(vue3Util.IBizPanelContainer);
    v.use(vue3Util.IBizPanelCtrlPos);
    v.use(vue3Util.IBizScrollContainer);
    v.use(index.IBizAuthUserinfo);
    v.use(index$1.IBizNavPosIndex);
    v.use(index$c.IBizNavTabs);
    v.use(index$d.IBizNavBreadcrumb);
    v.use(index$2.IBizPanelButton);
    v.use(vue3Util.IBizNavPos);
    v.use(index$3.IBizPanelAppTitle);
    v.use(vue3Util.IBizSingleDataContainer);
    v.use(vue3Util.IBizMultiDataContainer);
    v.use(vue3Util.IBizMultiDataContainerRaw);
    v.use(vue3Util.IBizPanelField);
    v.use(index$e.IBizPanelAppHeader);
    v.use(index$f.IBizPanelViewHeader);
    v.use(index$g.IBizPanelExpHeader);
    v.use(vue3Util.IBizPanelRawItem);
    v.use(index$h.IBizPanelViewContent);
    v.use(vue3Util.IBizGridContainer);
    v.use(index$4.IBizPanelTabPanel);
    v.use(vue3Util.IBizPanelTabPage);
    v.use(index$5.IBizSplitContainer);
    v.use(index$6.IBizPanelIndexViewSearch);
    v.use(index$i.IBizPanelAppLoginView);
    v.use(index$j.IBizPanelRememberMe);
    v.use(index$7.IBizIndexActions);
    v.use(index$k.IBizPanelContainerGroup);
    v.use(index$l.IBizUserMessage);
    v.use(vue3Util.IBizPanelContainerImage);
    v.use(index$m.IBizSearchFormButtons);
    v.use(vue3Util.IBizPanelItemRender);
    v.use(index$n.IBizViewMessage);
    v.use(index$o.IBizPanelStaticCarousel);
    v.use(vue3Util.IBizTeleportPlaceholder);
    v.use(vue3Util.IBizPanelContainerTabs);
    v.use(index$p.IBizCoopPos);
    v.use(index$q.IBizViewMsgPos);
    v.use(index$8.IBizUserAction);
    v.use(index$r.IBizDataImport);
    v.use(index$s.IBizShortCut);
    v.use(index$t.IBizAuthCaptcha);
    v.use(index$u.IBizPanelButtonList);
    v.use(vue3Util.IBizAuthWxmpQrcode);
    v.use(index$v.IBizAppSwitch);
    v.use(index$w.default);
  }
};

exports.IBizAuthUserinfo = index.IBizAuthUserinfo;
exports.IBizNavPosIndex = index$1.IBizNavPosIndex;
exports.IBizPanelButton = index$2.IBizPanelButton;
exports.IBizPanelAppTitle = index$3.IBizPanelAppTitle;
exports.IBizPanelTabPanel = index$4.IBizPanelTabPanel;
exports.IBizSplitContainer = index$5.IBizSplitContainer;
exports.IBizPanelIndexViewSearch = index$6.IBizPanelIndexViewSearch;
exports.IBizIndexActions = index$7.IBizIndexActions;
exports.IBizUserAction = index$8.IBizUserAction;
exports.NavPosIndexState = navPosIndex_state.NavPosIndexState;
exports.NavPosIndexController = navPosIndex_controller.NavPosIndexController;
exports.PanelButtonController = panelButton_controller.PanelButtonController;
exports.PanelAppTitleController = panelAppTitle_controller.PanelAppTitleController;
exports.SplitContainerController = splitContainer_controller.SplitContainerController;
exports.IBizPanelComponents = IBizPanelComponents;
exports.default = IBizPanelComponents;
