import { IBizPanelCtrlViewPageCaption, IBizPanelContainer, IBizPanelCtrlPos, IBizScrollContainer, IBizNavPos, IBizSingleDataContainer, IBizMultiDataContainer, IBizMultiDataContainerRaw, IBizPanelField, IBizPanelRawItem, IBizGridContainer, IBizPanelTabPage, IBizPanelContainerGroup, IBizPanelContainerImage, IBizPanelItemRender, IBizTeleportPlaceholder, IBizPanelContainerTabs, IBizAuthWxmpQrcode } from '@ibiz-template/vue3-util';
import { IBizAuthUserinfo } from './auth-userinfo/index.mjs';
import { IBizNavPosIndex } from './nav-pos-index/index.mjs';
import { IBizNavTabs } from './nav-tabs/index.mjs';
import { IBizNavBreadcrumb } from './nav-breadcrumb/index.mjs';
import { IBizPanelButton } from './panel-button/index.mjs';
import { IBizPanelAppTitle } from './panel-app-title/index.mjs';
import { IBizPanelAppHeader } from './panel-app-header/index.mjs';
import { IBizPanelViewHeader } from './panel-view-header/index.mjs';
import { IBizPanelExpHeader } from './panel-exp-header/index.mjs';
import { IBizPanelViewContent } from './panel-view-content/index.mjs';
import { IBizPanelTabPanel } from './panel-tab-panel/index.mjs';
import { IBizSplitContainer } from './split-container/index.mjs';
import { IBizPanelIndexViewSearch } from './panel-index-view-search/index.mjs';
import { IBizPanelAppLoginView } from './panel-app-login-view/index.mjs';
import { IBizPanelRememberMe } from './panel-remember-me/index.mjs';
import { IBizIndexActions } from './index-actions/index.mjs';
import { IBizUserMessage } from './user-message/index.mjs';
import { IBizSearchFormButtons } from './searchform-buttons/index.mjs';
import { IBizViewMessage } from './view-message/index.mjs';
import { IBizPanelStaticCarousel } from './panel-static-carousel/index.mjs';
import { IBizCoopPos } from './coop-pos/index.mjs';
import { IBizViewMsgPos } from './view-msg-pos/index.mjs';
import { IBizUserAction } from './user-action/index.mjs';
import { IBizDataImport } from './data-import/index.mjs';
import { IBizShortCut } from './short-cut/index.mjs';
import { IBizAuthCaptcha } from './auth-captcha/index.mjs';
import { IBizPanelButtonList } from './panel-button-list/index.mjs';
import { IBizAuthSso } from './auth-sso/index.mjs';
export { NavPosIndexState } from './nav-pos-index/nav-pos-index.state.mjs';
export { NavPosIndexController } from './nav-pos-index/nav-pos-index.controller.mjs';
export { PanelButtonController } from './panel-button/panel-button.controller.mjs';
export { PanelAppTitleController } from './panel-app-title/panel-app-title.controller.mjs';
export { SplitContainerController } from './split-container/split-container.controller.mjs';

"use strict";
const IBizPanelComponents = {
  install: (v) => {
    v.use(IBizAuthSso);
    v.use(IBizPanelCtrlViewPageCaption);
    v.use(IBizPanelContainer);
    v.use(IBizPanelCtrlPos);
    v.use(IBizScrollContainer);
    v.use(IBizAuthUserinfo);
    v.use(IBizNavPosIndex);
    v.use(IBizNavTabs);
    v.use(IBizNavBreadcrumb);
    v.use(IBizPanelButton);
    v.use(IBizNavPos);
    v.use(IBizPanelAppTitle);
    v.use(IBizSingleDataContainer);
    v.use(IBizMultiDataContainer);
    v.use(IBizMultiDataContainerRaw);
    v.use(IBizPanelField);
    v.use(IBizPanelAppHeader);
    v.use(IBizPanelViewHeader);
    v.use(IBizPanelExpHeader);
    v.use(IBizPanelRawItem);
    v.use(IBizPanelViewContent);
    v.use(IBizGridContainer);
    v.use(IBizPanelTabPanel);
    v.use(IBizPanelTabPage);
    v.use(IBizSplitContainer);
    v.use(IBizPanelIndexViewSearch);
    v.use(IBizPanelAppLoginView);
    v.use(IBizPanelRememberMe);
    v.use(IBizIndexActions);
    v.use(IBizPanelContainerGroup);
    v.use(IBizUserMessage);
    v.use(IBizPanelContainerImage);
    v.use(IBizSearchFormButtons);
    v.use(IBizPanelItemRender);
    v.use(IBizViewMessage);
    v.use(IBizPanelStaticCarousel);
    v.use(IBizTeleportPlaceholder);
    v.use(IBizPanelContainerTabs);
    v.use(IBizCoopPos);
    v.use(IBizViewMsgPos);
    v.use(IBizUserAction);
    v.use(IBizDataImport);
    v.use(IBizShortCut);
    v.use(IBizAuthCaptcha);
    v.use(IBizPanelButtonList);
    v.use(IBizAuthWxmpQrcode);
  }
};

export { IBizAuthUserinfo, IBizIndexActions, IBizNavPosIndex, IBizPanelAppTitle, IBizPanelButton, IBizPanelComponents, IBizPanelIndexViewSearch, IBizPanelTabPanel, IBizSplitContainer, IBizUserAction, IBizPanelComponents as default };
