import { PropType } from 'vue';
import { IViewMessage, ViewMsgController } from '@ibiz-template/runtime';
import './view-message.scss';
export declare const ViewMessage: import("vue").DefineComponent<{
    messages: {
        type: {
            (arrayLength: number): IViewMessage[];
            (...items: IViewMessage[]): IViewMessage[];
            new (arrayLength: number): IViewMessage[];
            new (...items: IViewMessage[]): IViewMessage[];
            isArray(arg: any): arg is any[];
            readonly prototype: any[];
            from<T>(arrayLike: ArrayLike<T>): T[];
            from<T_1, U>(arrayLike: ArrayLike<T_1>, mapfn: (v: T_1, k: number) => U, thisArg?: any): U[];
            from<T_2>(iterable: Iterable<T_2> | ArrayLike<T_2>): T_2[];
            from<T_3, U_1>(iterable: Iterable<T_3> | ArrayLike<T_3>, mapfn: (v: T_3, k: number) => U_1, thisArg?: any): U_1[];
            of<T_4>(...items: T_4[]): T_4[];
            readonly [Symbol.species]: ArrayConstructor;
        };
    };
    scroll: {
        type: BooleanConstructor;
        default: boolean;
    };
    context: {
        type: PropType<IContext>;
        required: false;
    };
    params: {
        type: PropType<IParams>;
        required: false;
    };
    controller: {
        type: PropType<ViewMsgController>;
    };
}, {
    ns: import("@ibiz-template/core").Namespace;
    getType: (messageType?: string) => string;
    items: import("vue").Ref<{
        key: string;
        position: string | undefined;
        messageType?: string | undefined;
        removeMode?: number | undefined;
        title?: string | undefined;
        message?: string | undefined;
        extraParams: IData;
        layoutPanel?: {
            codeName?: string | undefined;
            dataMode?: number | undefined;
            dataName?: string | undefined;
            dataTimer?: number | undefined;
            getControlAction?: {
                adappDELogicId?: string | undefined;
                actionDesc?: string | undefined;
                appDEMethodId?: string | undefined;
                appDataEntityId?: string | undefined;
                timeout?: number | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                codeName?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            } | undefined;
            layoutMode?: string | undefined;
            panelStyle?: string | undefined;
            panelWidth?: number | undefined;
            rootPanelItems?: {
                capLanguageRes?: {
                    defaultContent?: string | undefined;
                    lanResTag?: string | undefined;
                    lanResType?: string | undefined;
                    refFlag?: boolean | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                caption?: string | undefined;
                contentHeight?: number | undefined;
                contentWidth?: number | undefined;
                cssStyle?: string | undefined;
                dynaClass?: string | undefined;
                height?: number | undefined;
                itemStyle?: string | undefined;
                itemType?: string | undefined;
                labelCssStyle?: string | undefined;
                labelDynaClass?: string | undefined;
                labelSysCss?: {
                    codeName?: string | undefined;
                    cssName?: string | undefined;
                    cssStyle?: string | undefined;
                    designCssStyle?: string | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                layout?: {
                    layout?: string | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                layoutPos?: {
                    halignSelf?: string | undefined;
                    height?: number | undefined;
                    heightMode?: string | undefined;
                    layout?: string | undefined;
                    spacingBottom?: string | undefined;
                    spacingLeft?: string | undefined;
                    spacingRight?: string | undefined;
                    spacingTop?: string | undefined;
                    valignSelf?: string | undefined;
                    width?: number | undefined;
                    widthMode?: string | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                panelItemGroupLogics?: {
                    logicCat?: string | undefined;
                    relatedItemNames?: string[] | undefined;
                    groupOP?: string | undefined;
                    panelItemLogics?: {
                        logicCat?: string | undefined;
                        logicType?: string | undefined;
                        appId: string;
                        id?: string | undefined;
                        name?: string | undefined;
                        codeName?: string | undefined;
                        userParam?: Record<string, string> | undefined;
                        modelId?: string | undefined;
                        modelType?: string | undefined;
                    }[] | undefined;
                    notMode?: boolean | undefined;
                    logicType?: string | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                }[] | undefined;
                sysCss?: {
                    codeName?: string | undefined;
                    cssName?: string | undefined;
                    cssStyle?: string | undefined;
                    designCssStyle?: string | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                sysImage?: {
                    codeName?: string | undefined;
                    cssClass?: string | undefined;
                    cssClassX?: string | undefined;
                    glyph?: string | undefined;
                    height?: number | undefined;
                    imagePath?: string | undefined;
                    imagePathX?: string | undefined;
                    rawContent?: string | undefined;
                    width?: number | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                sysPFPluginId?: string | undefined;
                width?: number | undefined;
                showCaption?: boolean | undefined;
                controlAttributes?: {
                    attrName?: string | undefined;
                    attrValue?: string | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                }[] | undefined;
                controlLogics?: {
                    attrName?: string | undefined;
                    eventArg?: string | undefined;
                    eventArg2?: string | undefined;
                    eventNames?: string | undefined;
                    itemName?: string | undefined;
                    logicTag?: string | undefined;
                    logicType?: string | undefined;
                    appDEUIActionId?: string | undefined;
                    appDEUILogicId?: string | undefined;
                    appDataEntityId?: string | undefined;
                    appUILogicId?: string | undefined;
                    appViewEngineId?: string | undefined;
                    appViewLogicId?: string | undefined;
                    scriptCode?: string | undefined;
                    timer?: number | undefined;
                    triggerType?: string | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                }[] | undefined;
                controlRenders?: {
                    layoutPanelModel?: string | undefined;
                    layoutPanel?: any | undefined;
                    sysPFPluginId?: string | undefined;
                    renderName?: string | undefined;
                    renderType?: string | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                }[] | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                codeName?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            }[] | undefined;
            layoutPanel?: boolean | undefined;
            mobilePanel?: boolean | undefined;
            controlStyle?: string | undefined;
            controlType?: string | undefined;
            dynaSysMode?: number | undefined;
            height?: number | undefined;
            logicName?: string | undefined;
            appDataEntityId?: string | undefined;
            controlAttributes?: {
                attrName?: string | undefined;
                attrValue?: string | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                codeName?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            }[] | undefined;
            controlLogics?: {
                attrName?: string | undefined;
                eventArg?: string | undefined;
                eventArg2?: string | undefined;
                eventNames?: string | undefined;
                itemName?: string | undefined;
                logicTag?: string | undefined;
                logicType?: string | undefined;
                appDEUIActionId?: string | undefined;
                appDEUILogicId?: string | undefined;
                appDataEntityId?: string | undefined;
                appUILogicId?: string | undefined;
                appViewEngineId?: string | undefined;
                appViewLogicId?: string | undefined;
                scriptCode?: string | undefined;
                timer?: number | undefined;
                triggerType?: string | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                codeName?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            }[] | undefined;
            controlParam?: {
                ctrlParams?: {
                    [x: string]: any;
                    [x: symbol]: any;
                    constructor: Function;
                    toString: () => string;
                    toLocaleString: () => string;
                    valueOf: () => Object;
                    hasOwnProperty: (v: PropertyKey) => boolean;
                    isPrototypeOf: (v: Object) => boolean;
                    propertyIsEnumerable: (v: PropertyKey) => boolean;
                } | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                codeName?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            } | undefined;
            controlRenders?: {
                layoutPanelModel?: string | undefined;
                layoutPanel?: any | undefined;
                sysPFPluginId?: string | undefined;
                renderName?: string | undefined;
                renderType?: string | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                codeName?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            }[] | undefined;
            ctrlMsg?: {
                codeName?: string | undefined;
                msgModel?: string | undefined;
                ctrlMsgItems?: {
                    content?: string | undefined;
                    contentLanguageRes?: {
                        defaultContent?: string | undefined;
                        lanResTag?: string | undefined;
                        lanResType?: string | undefined;
                        refFlag?: boolean | undefined;
                        appId: string;
                        id?: string | undefined;
                        name?: string | undefined;
                        codeName?: string | undefined;
                        userParam?: Record<string, string> | undefined;
                        modelId?: string | undefined;
                        modelType?: string | undefined;
                    } | undefined;
                    timeout?: number | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                }[] | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            } | undefined;
            sysCss?: {
                codeName?: string | undefined;
                cssName?: string | undefined;
                cssStyle?: string | undefined;
                designCssStyle?: string | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            } | undefined;
            sysPFPluginId?: string | undefined;
            priority?: number | undefined;
            user2ControlAction?: {
                adappDELogicId?: string | undefined;
                actionDesc?: string | undefined;
                appDEMethodId?: string | undefined;
                appDataEntityId?: string | undefined;
                timeout?: number | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                codeName?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            } | undefined;
            userControlAction?: {
                adappDELogicId?: string | undefined;
                actionDesc?: string | undefined;
                appDEMethodId?: string | undefined;
                appDataEntityId?: string | undefined;
                timeout?: number | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                codeName?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            } | undefined;
            width?: number | undefined;
            appId: string;
            id?: string | undefined;
            name?: string | undefined;
            userParam?: Record<string, string> | undefined;
            modelId?: string | undefined;
            modelType?: string | undefined;
            appCounterRefs?: {
                appCounter?: {
                    getAppDEActionId?: string | undefined;
                    getAppDEDataSetId?: string | undefined;
                    appDataEntityId?: string | undefined;
                    codeName?: string | undefined;
                    counterData?: string | undefined;
                    counterData2?: string | undefined;
                    counterType?: string | undefined;
                    customCond?: string | undefined;
                    counterId?: string | undefined;
                    sysPFPluginId?: string | undefined;
                    timer?: number | undefined;
                    uniqueTag?: string | undefined;
                    navigateContexts?: {
                        desc?: string | undefined;
                        key?: string | undefined;
                        value?: string | undefined;
                        rawValue?: boolean | undefined;
                        appId: string;
                        id?: string | undefined;
                        name?: string | undefined;
                        codeName?: string | undefined;
                        userParam?: Record<string, string> | undefined;
                        modelId?: string | undefined;
                        modelType?: string | undefined;
                    }[] | undefined;
                    navigateParams?: {
                        desc?: string | undefined;
                        key?: string | undefined;
                        value?: string | undefined;
                        rawValue?: boolean | undefined;
                        appId: string;
                        id?: string | undefined;
                        name?: string | undefined;
                        codeName?: string | undefined;
                        userParam?: Record<string, string> | undefined;
                        modelId?: string | undefined;
                        modelType?: string | undefined;
                    }[] | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                refMode?: {
                    [x: string]: any;
                    [x: symbol]: any;
                    constructor: Function;
                    toString: () => string;
                    toLocaleString: () => string;
                    valueOf: () => Object;
                    hasOwnProperty: (v: PropertyKey) => boolean;
                    isPrototypeOf: (v: Object) => boolean;
                    propertyIsEnumerable: (v: PropertyKey) => boolean;
                } | undefined;
                tag?: string | undefined;
                uniqueTag?: string | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                codeName?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            }[] | undefined;
            appViewEngines?: {
                engineCat?: string | undefined;
                engineType?: string | undefined;
                params?: {
                    paramType?: string | undefined;
                    value?: {
                        [x: string]: any;
                        [x: symbol]: any;
                        constructor: Function;
                        toString: () => string;
                        toLocaleString: () => string;
                        valueOf: () => Object;
                        hasOwnProperty: (v: PropertyKey) => boolean;
                        isPrototypeOf: (v: Object) => boolean;
                        propertyIsEnumerable: (v: PropertyKey) => boolean;
                    } | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                }[] | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                codeName?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            }[] | undefined;
            appViewLogics?: {
                builtinAppUILogic?: {
                    appDEUILogicId?: string | undefined;
                    appDataEntityId?: string | undefined;
                    appUILogicRefViews?: {
                        openMode?: string | undefined;
                        refMode?: string | undefined;
                        refAppViewId?: string | undefined;
                        navigateContexts?: {
                            desc?: string | undefined;
                            key?: string | undefined;
                            value?: string | undefined;
                            rawValue?: boolean | undefined;
                            appId: string;
                            id?: string | undefined;
                            name?: string | undefined;
                            codeName?: string | undefined;
                            userParam?: Record<string, string> | undefined;
                            modelId?: string | undefined;
                            modelType?: string | undefined;
                        }[] | undefined;
                        navigateParams?: {
                            desc?: string | undefined;
                            key?: string | undefined;
                            value?: string | undefined;
                            rawValue?: boolean | undefined;
                            appId: string;
                            id?: string | undefined;
                            name?: string | undefined;
                            codeName?: string | undefined;
                            userParam?: Record<string, string> | undefined;
                            modelId?: string | undefined;
                            modelType?: string | undefined;
                        }[] | undefined;
                        appId: string;
                        id?: string | undefined;
                        name?: string | undefined;
                        codeName?: string | undefined;
                        userParam?: Record<string, string> | undefined;
                        modelId?: string | undefined;
                        modelType?: string | undefined;
                    }[] | undefined;
                    sysPFPluginId?: string | undefined;
                    viewLogicType?: string | undefined;
                    builtinLogic?: boolean | undefined;
                    codeName?: string | undefined;
                    logicType?: string | undefined;
                    viewLogicStyle?: string | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                attrName?: string | undefined;
                eventArg?: string | undefined;
                eventArg2?: string | undefined;
                eventNames?: string | undefined;
                itemName?: string | undefined;
                logicParam?: string | undefined;
                logicParam2?: string | undefined;
                logicTrigger?: string | undefined;
                logicType?: string | undefined;
                owner?: {
                    [x: string]: any;
                    [x: symbol]: any;
                    constructor: Function;
                    toString: () => string;
                    toLocaleString: () => string;
                    valueOf: () => Object;
                    hasOwnProperty: (v: PropertyKey) => boolean;
                    isPrototypeOf: (v: Object) => boolean;
                    propertyIsEnumerable: (v: PropertyKey) => boolean;
                } | undefined;
                appDEUIActionId?: string | undefined;
                appDEUILogicId?: string | undefined;
                appDataEntityId?: string | undefined;
                appUILogicId?: string | undefined;
                appViewEngineId?: string | undefined;
                appViewLogicId?: string | undefined;
                sysPFPluginId?: string | undefined;
                ctrlName?: string | undefined;
                scriptCode?: string | undefined;
                timer?: number | undefined;
                builtinLogic?: boolean | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                codeName?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            }[] | undefined;
            appViewRefs?: {
                height?: number | undefined;
                openMode?: string | undefined;
                owner?: {
                    [x: string]: any;
                    [x: symbol]: any;
                    constructor: Function;
                    toString: () => string;
                    toLocaleString: () => string;
                    valueOf: () => Object;
                    hasOwnProperty: (v: PropertyKey) => boolean;
                    isPrototypeOf: (v: Object) => boolean;
                    propertyIsEnumerable: (v: PropertyKey) => boolean;
                } | undefined;
                parentDataJO?: {
                    [x: string]: any;
                    [x: symbol]: any;
                    constructor: Function;
                    toString: () => string;
                    toLocaleString: () => string;
                    valueOf: () => Object;
                    hasOwnProperty: (v: PropertyKey) => boolean;
                    isPrototypeOf: (v: Object) => boolean;
                    propertyIsEnumerable: (v: PropertyKey) => boolean;
                } | undefined;
                realOpenMode?: string | undefined;
                realTitle?: string | undefined;
                realTitleLanguageRes?: {
                    defaultContent?: string | undefined;
                    lanResTag?: string | undefined;
                    lanResType?: string | undefined;
                    refFlag?: boolean | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                refAppViewId?: string | undefined;
                viewParamJO?: {
                    [x: string]: any;
                    [x: symbol]: any;
                    constructor: Function;
                    toString: () => string;
                    toLocaleString: () => string;
                    valueOf: () => Object;
                    hasOwnProperty: (v: PropertyKey) => boolean;
                    isPrototypeOf: (v: Object) => boolean;
                    propertyIsEnumerable: (v: PropertyKey) => boolean;
                } | undefined;
                width?: number | undefined;
                navigateContexts?: {
                    desc?: string | undefined;
                    key?: string | undefined;
                    value?: string | undefined;
                    rawValue?: boolean | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                }[] | undefined;
                navigateParams?: {
                    desc?: string | undefined;
                    key?: string | undefined;
                    value?: string | undefined;
                    rawValue?: boolean | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                }[] | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                codeName?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            }[] | undefined;
            controls?: {
                codeName?: string | undefined;
                controlStyle?: string | undefined;
                controlType?: string | undefined;
                dynaSysMode?: number | undefined;
                height?: number | undefined;
                logicName?: string | undefined;
                appDataEntityId?: string | undefined;
                controlAttributes?: {
                    attrName?: string | undefined;
                    attrValue?: string | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                }[] | undefined;
                controlLogics?: {
                    attrName?: string | undefined;
                    eventArg?: string | undefined;
                    eventArg2?: string | undefined;
                    eventNames?: string | undefined;
                    itemName?: string | undefined;
                    logicTag?: string | undefined;
                    logicType?: string | undefined;
                    appDEUIActionId?: string | undefined;
                    appDEUILogicId?: string | undefined;
                    appDataEntityId?: string | undefined;
                    appUILogicId?: string | undefined;
                    appViewEngineId?: string | undefined;
                    appViewLogicId?: string | undefined;
                    scriptCode?: string | undefined;
                    timer?: number | undefined;
                    triggerType?: string | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                }[] | undefined;
                controlParam?: {
                    ctrlParams?: {
                        [x: string]: any;
                        [x: symbol]: any;
                        constructor: Function;
                        toString: () => string;
                        toLocaleString: () => string;
                        valueOf: () => Object;
                        hasOwnProperty: (v: PropertyKey) => boolean;
                        isPrototypeOf: (v: Object) => boolean;
                        propertyIsEnumerable: (v: PropertyKey) => boolean;
                    } | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                controlRenders?: {
                    layoutPanelModel?: string | undefined;
                    layoutPanel?: any | undefined;
                    sysPFPluginId?: string | undefined;
                    renderName?: string | undefined;
                    renderType?: string | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                }[] | undefined;
                ctrlMsg?: {
                    codeName?: string | undefined;
                    msgModel?: string | undefined;
                    ctrlMsgItems?: {
                        content?: string | undefined;
                        contentLanguageRes?: {
                            defaultContent?: string | undefined;
                            lanResTag?: string | undefined;
                            lanResType?: string | undefined;
                            refFlag?: boolean | undefined;
                            appId: string;
                            id?: string | undefined;
                            name?: string | undefined;
                            codeName?: string | undefined;
                            userParam?: Record<string, string> | undefined;
                            modelId?: string | undefined;
                            modelType?: string | undefined;
                        } | undefined;
                        timeout?: number | undefined;
                        appId: string;
                        id?: string | undefined;
                        name?: string | undefined;
                        codeName?: string | undefined;
                        userParam?: Record<string, string> | undefined;
                        modelId?: string | undefined;
                        modelType?: string | undefined;
                    }[] | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                sysCss?: {
                    codeName?: string | undefined;
                    cssName?: string | undefined;
                    cssStyle?: string | undefined;
                    designCssStyle?: string | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                sysPFPluginId?: string | undefined;
                priority?: number | undefined;
                user2ControlAction?: {
                    adappDELogicId?: string | undefined;
                    actionDesc?: string | undefined;
                    appDEMethodId?: string | undefined;
                    appDataEntityId?: string | undefined;
                    timeout?: number | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                userControlAction?: {
                    adappDELogicId?: string | undefined;
                    actionDesc?: string | undefined;
                    appDEMethodId?: string | undefined;
                    appDataEntityId?: string | undefined;
                    timeout?: number | undefined;
                    appId: string;
                    id?: string | undefined;
                    name?: string | undefined;
                    codeName?: string | undefined;
                    userParam?: Record<string, string> | undefined;
                    modelId?: string | undefined;
                    modelType?: string | undefined;
                } | undefined;
                width?: number | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            }[] | undefined;
            layout?: {
                layout?: string | undefined;
                appId: string;
                id?: string | undefined;
                name?: string | undefined;
                codeName?: string | undefined;
                userParam?: Record<string, string> | undefined;
                modelId?: string | undefined;
                modelType?: string | undefined;
            } | undefined;
        } | undefined;
        data?: IData | undefined;
        visible?: boolean | undefined;
        sysCss?: {
            codeName?: string | undefined;
            cssName?: string | undefined;
            cssStyle?: string | undefined;
            designCssStyle?: string | undefined;
            appId: string;
            id?: string | undefined;
            name?: string | undefined;
            userParam?: Record<string, string> | undefined;
            modelId?: string | undefined;
            modelType?: string | undefined;
        } | undefined;
        hidden?: boolean | undefined;
    }[]>;
    container: import("vue").Ref<HTMLElement | null>;
    carouselHeight: import("vue").Ref<string>;
    initialIndex: import("vue").Ref<number>;
    uuid: import("vue").Ref<string>;
    isHiddenContainer: import("vue").Ref<boolean>;
    handleAlertClose: (index: number) => void;
    handleChange: (index: number) => void;
}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
    messages: {
        type: {
            (arrayLength: number): IViewMessage[];
            (...items: IViewMessage[]): IViewMessage[];
            new (arrayLength: number): IViewMessage[];
            new (...items: IViewMessage[]): IViewMessage[];
            isArray(arg: any): arg is any[];
            readonly prototype: any[];
            from<T>(arrayLike: ArrayLike<T>): T[];
            from<T_1, U>(arrayLike: ArrayLike<T_1>, mapfn: (v: T_1, k: number) => U, thisArg?: any): U[];
            from<T_2>(iterable: Iterable<T_2> | ArrayLike<T_2>): T_2[];
            from<T_3, U_1>(iterable: Iterable<T_3> | ArrayLike<T_3>, mapfn: (v: T_3, k: number) => U_1, thisArg?: any): U_1[];
            of<T_4>(...items: T_4[]): T_4[];
            readonly [Symbol.species]: ArrayConstructor;
        };
    };
    scroll: {
        type: BooleanConstructor;
        default: boolean;
    };
    context: {
        type: PropType<IContext>;
        required: false;
    };
    params: {
        type: PropType<IParams>;
        required: false;
    };
    controller: {
        type: PropType<ViewMsgController>;
    };
}>>, {
    scroll: boolean;
}, {}>;
