'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var vue3Util = require('@ibiz-template/vue3-util');
var runtime = require('@ibiz-template/runtime');
var index$1 = require('./common/index.cjs');
var index$2 = require('./panel-component/index.cjs');
require('./control/index.cjs');
var index$E = require('./editor/index.cjs');
require('./view/index.cjs');
var index = require('./locale/index.cjs');
var index$3 = require('./view-engine/index.cjs');
var _404View = require('./view/404-view/404-view.cjs');
var _403View = require('./view/403-view/403-view.cjs');
var index$4 = require('./view/wf-step-trace-view/index.cjs');
var index$5 = require('./view/sub-app-ref-view/index.cjs');
var index$6 = require('./control/data-view/index.cjs');
var index$7 = require('./control/tree/index.cjs');
var index$8 = require('./control/app-menu/index.cjs');
var index$9 = require('./control/app-menu-icon-view/index.cjs');
var index$a = require('./control/grid/grid/index.cjs');
var index$b = require('./control/tree-grid/index.cjs');
var index$c = require('./control/list/index.cjs');
var index$d = require('./control/chart/index.cjs');
var index$e = require('./control/pickup-view-panel/index.cjs');
var index$f = require('./control/toolbar/index.cjs');
var index$g = require('./control/form/form/index.cjs');
var index$h = require('./control/exp-bar/list-exp-bar/index.cjs');
var index$i = require('./control/exp-bar/data-view-exp-bar/index.cjs');
var index$j = require('./control/exp-bar/grid-exp-bar/index.cjs');
var index$k = require('./control/form/search-form/index.cjs');
var index$l = require('./control/form/edit-form/index.cjs');
var index$m = require('./control/caption-bar/index.cjs');
var index$n = require('./control/tab-exp-panel/index.cjs');
var index$o = require('./control/exp-bar/tree-exp-bar/index.cjs');
var index$p = require('./control/search-bar/index.cjs');
var index$q = require('./control/wizard-panel/index.cjs');
var index$r = require('./control/drbar/index.cjs');
var index$s = require('./control/drtab/index.cjs');
var index$t = require('./control/dashboard/index.cjs');
var index$u = require('./control/calendar/index.cjs');
var index$v = require('./control/exp-bar/calendar-exp-bar/index.cjs');
var index$w = require('./control/kanban/index.cjs');
var index$x = require('./control/tree-grid-ex/index.cjs');
var index$y = require('./control/medit-view-panel/index.cjs');
var index$z = require('./control/exp-bar/chart-exp-bar/index.cjs');
var index$A = require('./control/map/index.cjs');
var index$B = require('./control/report-panel/index.cjs');
var index$C = require('./control/gantt/index.cjs');
var index$D = require('./control/context-menu/index.cjs');

"use strict";
var IBizVue3 = {
  install: (v) => {
    ibiz.i18n = index.iBizI18n;
    ibiz.util.getExcelUtil = () => Promise.resolve().then(function () { return require('./util/xlsx-util/xlsx-util.cjs'); });
    runtime.registerErrorViewProvider("404", () => ({ component: _404View.View404 }));
    runtime.registerErrorViewProvider("403", () => ({ component: _403View.View403 }));
    v.use(index$1.IBizCommonComponents);
    v.use(index$2.IBizPanelComponents);
    v.use(index$3.IBizViewEngine);
    v.use(vue3Util.IBizView);
    v.use(vue3Util.IBizPortalView);
    v.use(vue3Util.IBizHtmlView);
    v.use(index$4.IBizWFStepTraceView);
    v.use(vue3Util.IBizDeRedirectView);
    v.use(index$5.IBizSubAppRefView);
    v.use(index$6.IBizDataViewControl);
    v.use(index$7.IBizTreeControl);
    v.use(index$8.IBizAppMenuControl);
    v.use(index$9.IBizAppMenuIconViewControl);
    v.use(index$a.IBizGridControl);
    v.use(index$b.IBizTreeGridControl);
    v.use(index$c.IBizListControl);
    v.use(index$d.IBizChartControl);
    v.use(index$e.IBizPickupViewPanelControl);
    v.use(index$f.IBizToolbarControl);
    v.use(vue3Util.IBizViewLayoutPanelControl);
    v.use(vue3Util.IBizPanelControl);
    v.use(index$g.IBizFormControl);
    v.use(index$h.IBizListExpBarControl);
    v.use(index$i.IBizDataViewExpBarControl);
    v.use(index$j.IBizGridExpBarControl);
    v.use(index$k.IBizSearchFormControl);
    v.use(index$l.IBizEditFormControl);
    v.use(index$m.IBizCaptionBarControl);
    v.use(index$n.IBizTabExpPanelControl);
    v.use(index$o.IBizTreeExpBarControl);
    v.use(index$p.IBizSearchBarControl);
    v.use(index$q.IBizWizardPanelControl);
    v.use(index$r.IBizDRBarControl);
    v.use(index$s.IBizDRTabControl);
    v.use(index$t.IBizDashboardControl);
    v.use(index$u.IBizCalendarControl);
    v.use(index$v.IBizCalendarExpBarControl);
    v.use(index$w.IBizKanbanControl);
    v.use(index$x.IBizTreeGridExControl);
    v.use(index$y.IBizMEditViewPanelControl);
    v.use(index$z.IBizChartExpBarControl);
    v.use(index$A.IBizMapControl);
    v.use(index$B.IBizReportPanelControl);
    v.use(index$C.IBizGanttControl);
    v.use(index$D.IBizContextMenuControl);
    v.use(index$E.IBizEditor);
  }
};

exports.default = IBizVue3;
