'use strict';

var appIndexViewLayoutNoNav = require('./app-index-view-layout-no-nav.cjs');
var appIndexViewLayoutTopNonav = require('./app-index-view-layout-top-nonav.cjs');
var appIndexViewLayoutBlankMode = require('./app-index-view-layout-blank-mode.cjs');
var appIndexViewLayoutCenter = require('./app-index-view-layout-center.cjs');
var appIndexViewLayoutTop = require('./app-index-view-layout-top.cjs');
var appIndexViewLayout = require('./app-index-view-layout.cjs');
var appLoginView = require('./app-login-view.cjs');
var appDataUploadView = require('./app-data-upload-view.cjs');
var appStartViewLayout = require('./app-start-view-layout.cjs');
var appWelcomeViewLayout = require('./app-welcome-view-layout.cjs');
var viewLayoutModelRepositoryDeChartViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-chart-view-layout.cjs');
var viewLayoutModelRepositoryDeCalendarExpViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-calendar-exp-view-layout.cjs');
var viewLayoutModelRepositoryDeCalendarViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-calendar-view-layout.cjs');
var viewLayoutModelRepositoryDeDataViewExpViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-data-view-exp-view-layout.cjs');
var viewLayoutModelRepositoryDeDataViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-data-view-layout.cjs');
var viewLayoutModelRepositoryDeKanbanViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-kanban-view-layout.cjs');
var viewLayoutModelRepositoryDeEditView2Layout = require('./view-layout-model-repository/view-layout-model-repository-de-edit-view-2-layout.cjs');
var viewLayoutModelRepositoryDeEditView3Layout = require('./view-layout-model-repository/view-layout-model-repository-de-edit-view-3-layout.cjs');
var viewLayoutModelRepositoryDeEditView4Layout = require('./view-layout-model-repository/view-layout-model-repository-de-edit-view-4-layout.cjs');
var viewLayoutModelRepositoryFormPickupDataView = require('./view-layout-model-repository/view-layout-model-repository-form-pickup-data-view.cjs');
var viewLayoutModelRepositoryDeEditViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-edit-view-layout.cjs');
var viewLayoutModelRepositoryDeGridExpViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-grid-exp-view-layout.cjs');
var viewLayoutModelRepositoryDeGridViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-grid-view-layout.cjs');
var viewLayoutModelRepositoryDeListExpViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-list-exp-view-layout.cjs');
var viewLayoutModelRepositoryDeListViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-list-view-layout.cjs');
var viewLayoutModelRepositoryDeOptionViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-option-view-layout.cjs');
var viewLayoutModelRepositoryDePickupGridViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-pickup-grid-view-layout.cjs');
var viewLayoutModelRepositoryDePickupTreeViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-pickup-tree-view-layout.cjs');
var viewLayoutModelRepositoryDePickupView2Layout = require('./view-layout-model-repository/view-layout-model-repository-de-pickup-view-2-layout.cjs');
var viewLayoutModelRepositoryDePickupViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-pickup-view-layout.cjs');
var viewLayoutModelRepositoryDeTabExpViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-tab-exp-view-layout.cjs');
var viewLayoutModelRepositoryDeTreeExpViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-tree-exp-view-layout.cjs');
var viewLayoutModelRepositoryDeTreeViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-tree-view-layout.cjs');
var viewLayoutModelRepositoryDeWizardViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-wizard-view-layout.cjs');
var viewLayoutModelRepositoryDemPickupViewLayout = require('./view-layout-model-repository/view-layout-model-repository-dem-pickup-view-layout.cjs');
var viewLayoutModelRepositoryDemPickupView2Layout = require('./view-layout-model-repository/view-layout-model-repository-dem-pickup-view-2-layout.cjs');
var viewLayoutModelRepositoryDewfDynaActionViewLayout = require('./view-layout-model-repository/view-layout-model-repository-dewf-dyna-action-view-layout.cjs');
var viewLayoutModelRepositoryDewfDynaStartViewLayout = require('./view-layout-model-repository/view-layout-model-repository-dewf-dyna-start-view-layout.cjs');
var viewLayoutModelRepositoryDewfDynaEditView3Layout = require('./view-layout-model-repository/view-layout-model-repository-dewf-dyna-edit-view-3-layout.cjs');
var viewLayoutModelRepositoryDewfDynaEditViewLayout = require('./view-layout-model-repository/view-layout-model-repository-dewf-dyna-edit-view-layout.cjs');
var viewLayoutModelRepositoryDePanelViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-panel-view-layout.cjs');
var viewLayoutModelRepositoryDePickupDataViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-pickup-data-view-layout.cjs');
var viewLayoutModelRepositoryDeIndexPickupDataViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-index-pickup-data-view-layout.cjs');
var viewLayoutModelRepositoryDeTreeGridExViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-tree-grid-ex-view-layout.cjs');
var viewLayoutModelRepositoryDeTreeGridViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-tree-grid-view-layout.cjs');
var viewLayoutModelRepositoryDemEditView9Layout = require('./view-layout-model-repository/view-layout-model-repository-dem-edit-view-9-layout.cjs');
var viewLayoutModelRepositoryDeChartExpViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-chart-exp-view-layout.cjs');
var viewLayoutModelRepositoryDeMapViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-map-view-layout.cjs');
var viewLayoutModelRepositoryDeReportViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-report-view-layout.cjs');
var viewLayoutModelRepositoryDeGanttViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-gantt-view-layout.cjs');
var viewLayoutModelRepositoryDeIndexViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-index-view-layout.cjs');
var viewLayoutModelRepositoryDeTabSearchViewViewLayout = require('./view-layout-model-repository/view-layout-model-repository-de-tab-search-view-view-layout.cjs');
var viewLayoutModelRepositoryDeTabExpViewLayoutFlow = require('./view-layout-model-repository/view-layout-model-repository-de-tab-exp-view-layout-flow.cjs');
var viewLayoutModelRepositoryDemEditView9LayoutTop = require('./view-layout-model-repository/view-layout-model-repository-dem-edit-view-9-layout-top.cjs');
var viewLayoutModelRepositoryAppPanelViewLayout = require('./view-layout-model-repository/view-layout-model-repository-app-panel-view-layout.cjs');
var controlLayoutModelRepositoryGridExpBarLayout = require('./control-layout/control-layout-model-repository-grid-exp-bar-layout.cjs');
var controlLayoutModelRepositoryListExpBarLayout = require('./control-layout/control-layout-model-repository-list-exp-bar-layout.cjs');
var controlLayoutModelRepositoryDataViewExpBarLayout = require('./control-layout/control-layout-model-repository-data-view-exp-bar-layout.cjs');
var controlLayoutModelRepositoryTreeExpBarLayout = require('./control-layout/control-layout-model-repository-tree-exp-bar-layout.cjs');
var controlLayoutModelRepositoryChartExpBarLayout = require('./control-layout/control-layout-model-repository-chart-exp-bar-layout.cjs');
var controlLayoutModelRepositorySearchFormLayout = require('./control-layout/control-layout-model-repository-search-form-layout.cjs');
var controlLayoutModelRepositoryTreeLayout = require('./control-layout/control-layout-model-repository-tree-layout.cjs');
var controlLayoutModelRepositoryDataViewLayout = require('./control-layout/control-layout-model-repository-data-view-layout.cjs');
var controlLayoutModelRepositoryCalendarExpBarLayout = require('./control-layout/control-layout-model-repository-calendar-exp-bar-layout.cjs');

"use strict";
function install(callBack) {
  callBack("APPINDEXVIEW_DEFAULT", appIndexViewLayout.default);
  callBack("APPINDEXVIEW_DEFAULT_LEFT", appIndexViewLayout.default);
  callBack("APPINDEXVIEW_DEFAULT_BLANK_MODE", appIndexViewLayoutBlankMode.default);
  callBack("APPINDEXVIEW_DEFAULT_CENTER", appIndexViewLayoutCenter.default);
  callBack("APPINDEXVIEW_DEFAULT_TOP", appIndexViewLayoutTop.default);
  callBack("APPINDEXVIEW_DEFAULT_NO_NAV", appIndexViewLayoutNoNav.default);
  callBack("APPINDEXVIEW_DEFAULT_LEFT_NO_NAV", appIndexViewLayoutNoNav.default);
  callBack("APPINDEXVIEW_DEFAULT_TOP_NO_NAV", appIndexViewLayoutTopNonav.default);
  callBack("APPLOGINVIEW_DEFAULT", appLoginView.default);
  callBack("APPDATAUPLOADVIEW_DEFAULT", appDataUploadView.default);
  callBack("APPSTARTVIEW_DEFAULT", appStartViewLayout.default);
  callBack("APPWELCOMEVIEW_DEFAULT", appWelcomeViewLayout.default);
  callBack("DECHARTVIEW_DEFAULT", viewLayoutModelRepositoryDeChartViewLayout.default);
  callBack("DECHARTVIEW9_DEFAULT", viewLayoutModelRepositoryDeChartViewLayout.default);
  callBack("DECALENDAREXPVIEW_DEFAULT", viewLayoutModelRepositoryDeCalendarExpViewLayout.default);
  callBack("DECALENDARVIEW_DEFAULT", viewLayoutModelRepositoryDeCalendarViewLayout.default);
  callBack("DECALENDARVIEW9_DEFAULT", viewLayoutModelRepositoryDeCalendarViewLayout.default);
  callBack("DEDATAVIEWEXPVIEW_DEFAULT", viewLayoutModelRepositoryDeDataViewExpViewLayout.default);
  callBack("DEDATAVIEW_DEFAULT", viewLayoutModelRepositoryDeDataViewLayout.default);
  callBack("DEDATAVIEW9_DEFAULT", viewLayoutModelRepositoryDeDataViewLayout.default);
  callBack("DEKANBANVIEW_DEFAULT", viewLayoutModelRepositoryDeKanbanViewLayout.default);
  callBack("DEEDITVIEW2_DEFAULT", viewLayoutModelRepositoryDeEditView2Layout.default);
  callBack("DEEDITVIEW3_DEFAULT", viewLayoutModelRepositoryDeEditView3Layout.default);
  callBack("DEEDITVIEW4_DEFAULT", viewLayoutModelRepositoryDeEditView4Layout.default);
  callBack("DEFORMPICKUPDATAVIEW_DEFAULT", viewLayoutModelRepositoryFormPickupDataView.default);
  callBack("DEEDITVIEW_DEFAULT", viewLayoutModelRepositoryDeEditViewLayout.default);
  callBack("DEEDITVIEW9_DEFAULT", viewLayoutModelRepositoryDeEditViewLayout.default);
  callBack("DEGRIDEXPVIEW_DEFAULT", viewLayoutModelRepositoryDeGridExpViewLayout.default);
  callBack("DEGRIDVIEW_DEFAULT", viewLayoutModelRepositoryDeGridViewLayout.default);
  callBack("DEGRIDVIEW9_DEFAULT", viewLayoutModelRepositoryDeGridViewLayout.default);
  callBack("DELISTEXPVIEW_DEFAULT", viewLayoutModelRepositoryDeListExpViewLayout.default);
  callBack("DELISTVIEW_DEFAULT", viewLayoutModelRepositoryDeListViewLayout.default);
  callBack("DELISTVIEW9_DEFAULT", viewLayoutModelRepositoryDeListViewLayout.default);
  callBack("DEOPTVIEW_DEFAULT", viewLayoutModelRepositoryDeOptionViewLayout.default);
  callBack("DEPICKUPGRIDVIEW_DEFAULT", viewLayoutModelRepositoryDePickupGridViewLayout.default);
  callBack("DEPICKUPTREEVIEW_DEFAULT", viewLayoutModelRepositoryDePickupTreeViewLayout.default);
  callBack("DEPICKUPVIEW2_DEFAULT", viewLayoutModelRepositoryDePickupView2Layout.default);
  callBack("DEPICKUPVIEW_DEFAULT", viewLayoutModelRepositoryDePickupViewLayout.default);
  callBack("DETABEXPVIEW_DEFAULT", viewLayoutModelRepositoryDeTabExpViewLayout.default);
  callBack("DETABEXPVIEW9_DEFAULT", viewLayoutModelRepositoryDeTabExpViewLayout.default);
  callBack("DETREEEXPVIEW_DEFAULT", viewLayoutModelRepositoryDeTreeExpViewLayout.default);
  callBack("DETREEVIEW_DEFAULT", viewLayoutModelRepositoryDeTreeViewLayout.default);
  callBack("DETREEVIEW9_DEFAULT", viewLayoutModelRepositoryDeTreeViewLayout.default);
  callBack("DEWIZARDVIEW_DEFAULT", viewLayoutModelRepositoryDeWizardViewLayout.default);
  callBack("DEMPICKUPVIEW_DEFAULT", viewLayoutModelRepositoryDemPickupViewLayout.default);
  callBack("DEMPICKUPVIEW2_DEFAULT", viewLayoutModelRepositoryDemPickupView2Layout.default);
  callBack("DEWFDYNAACTIONVIEW_DEFAULT", viewLayoutModelRepositoryDewfDynaActionViewLayout.default);
  callBack("DEWFDYNASTARTVIEW_DEFAULT", viewLayoutModelRepositoryDewfDynaStartViewLayout.default);
  callBack("DEWFDYNAEDITVIEW3_DEFAULT", viewLayoutModelRepositoryDewfDynaEditView3Layout.default);
  callBack("DEWFDYNAEDITVIEW_DEFAULT", viewLayoutModelRepositoryDewfDynaEditViewLayout.default);
  callBack("DEPANELVIEW_DEFAULT", viewLayoutModelRepositoryDePanelViewLayout.default);
  callBack("DEPICKUPDATAVIEW_DEFAULT", viewLayoutModelRepositoryDePickupDataViewLayout.default);
  callBack("DEINDEXPICKUPDATAVIEW_DEFAULT", viewLayoutModelRepositoryDeIndexPickupDataViewLayout.default);
  callBack("DETREEGRIDEXVIEW_DEFAULT", viewLayoutModelRepositoryDeTreeGridExViewLayout.default);
  callBack("DETREEGRIDVIEW_DEFAULT", viewLayoutModelRepositoryDeTreeGridViewLayout.default);
  callBack("DEMEDITVIEW9_DEFAULT", viewLayoutModelRepositoryDemEditView9Layout.default);
  callBack("DECHARTEXPVIEW_DEFAULT", viewLayoutModelRepositoryDeChartExpViewLayout.default);
  callBack("DEMAPVIEW_DEFAULT", viewLayoutModelRepositoryDeMapViewLayout.default);
  callBack("DEREPORTVIEW_DEFAULT", viewLayoutModelRepositoryDeReportViewLayout.default);
  callBack("DEGANTTVIEW_DEFAULT", viewLayoutModelRepositoryDeGanttViewLayout.default);
  callBack("DEINDEXVIEW_DEFAULT", viewLayoutModelRepositoryDeIndexViewLayout.default);
  callBack("DETABSEARCHVIEW_DEFAULT", viewLayoutModelRepositoryDeTabSearchViewViewLayout.default);
  callBack("DETABEXPVIEW_FLOW", viewLayoutModelRepositoryDeTabExpViewLayoutFlow.default);
  callBack("DEMEDITVIEW9_TOP", viewLayoutModelRepositoryDemEditView9LayoutTop.default);
  callBack("GRIDEXPBAR_DEFAULT", controlLayoutModelRepositoryGridExpBarLayout.default);
  callBack("LISTEXPBAR_DEFAULT", controlLayoutModelRepositoryListExpBarLayout.default);
  callBack("DATAVIEWEXPBAR_DEFAULT", controlLayoutModelRepositoryDataViewExpBarLayout.default);
  callBack("TREEEXPBAR_DEFAULT", controlLayoutModelRepositoryTreeExpBarLayout.default);
  callBack("CHARTEXPBAR_DEFAULT", controlLayoutModelRepositoryChartExpBarLayout.default);
  callBack("SEARCHFORM_DEFAULT", controlLayoutModelRepositorySearchFormLayout.default);
  callBack("TREEVIEW_DEFAULT", controlLayoutModelRepositoryTreeLayout.default);
  callBack("DATAVIEW_DEFAULT", controlLayoutModelRepositoryDataViewLayout.default);
  callBack("CALENDAREXPBAR_DEFAULT", controlLayoutModelRepositoryCalendarExpBarLayout.default);
  callBack("APPPANELVIEW_DEFAULT", viewLayoutModelRepositoryAppPanelViewLayout.default);
}

exports.install = install;
