import { IBizView, IBizPortalView, IBizHtmlView, IBizDeRedirectView, IBizViewLayoutPanelControl, IBizPanelControl } from '@ibiz-template/vue3-util';
import { registerErrorViewProvider } from '@ibiz-template/runtime';
import { IBizCommonComponents } from './common/index.mjs';
import { IBizPanelComponents } from './panel-component/index.mjs';
import './control/index.mjs';
import { IBizEditor } from './editor/index.mjs';
import './view/index.mjs';
import { iBizI18n } from './locale/index.mjs';
import { IBizDirectives } from './directives/index.mjs';
import { IBizViewEngine } from './view-engine/index.mjs';
import { View404 } from './view/404-view/404-view.mjs';
import { View403 } from './view/403-view/403-view.mjs';
import { IBizWFStepTraceView } from './view/wf-step-trace-view/index.mjs';
import { IBizSubAppRefView } from './view/sub-app-ref-view/index.mjs';
import { IBizDataViewControl } from './control/data-view/index.mjs';
import { IBizTreeControl } from './control/tree/index.mjs';
import { IBizAppMenuControl } from './control/app-menu/index.mjs';
import { IBizAppMenuIconViewControl } from './control/app-menu-icon-view/index.mjs';
import { IBizGridControl } from './control/grid/grid/index.mjs';
import { IBizTreeGridControl } from './control/tree-grid/index.mjs';
import { IBizListControl } from './control/list/index.mjs';
import { IBizChartControl } from './control/chart/index.mjs';
import { IBizPickupViewPanelControl } from './control/pickup-view-panel/index.mjs';
import { IBizToolbarControl } from './control/toolbar/index.mjs';
import { IBizFormControl } from './control/form/form/index.mjs';
import { IBizListExpBarControl } from './control/exp-bar/list-exp-bar/index.mjs';
import { IBizDataViewExpBarControl } from './control/exp-bar/data-view-exp-bar/index.mjs';
import { IBizGridExpBarControl } from './control/exp-bar/grid-exp-bar/index.mjs';
import { IBizSearchFormControl } from './control/form/search-form/index.mjs';
import { IBizEditFormControl } from './control/form/edit-form/index.mjs';
import { IBizCaptionBarControl } from './control/caption-bar/index.mjs';
import { IBizTabExpPanelControl } from './control/tab-exp-panel/index.mjs';
import { IBizTreeExpBarControl } from './control/exp-bar/tree-exp-bar/index.mjs';
import { IBizSearchBarControl } from './control/search-bar/index.mjs';
import { IBizWizardPanelControl } from './control/wizard-panel/index.mjs';
import { IBizDRBarControl } from './control/drbar/index.mjs';
import { IBizDRTabControl } from './control/drtab/index.mjs';
import { IBizDashboardControl } from './control/dashboard/index.mjs';
import { IBizCalendarControl } from './control/calendar/index.mjs';
import { IBizCalendarExpBarControl } from './control/exp-bar/calendar-exp-bar/index.mjs';
import { IBizKanbanControl } from './control/kanban/index.mjs';
import { IBizTreeGridExControl } from './control/tree-grid-ex/index.mjs';
import { IBizMEditViewPanelControl } from './control/medit-view-panel/index.mjs';
import { IBizChartExpBarControl } from './control/exp-bar/chart-exp-bar/index.mjs';
import { IBizMapControl } from './control/map/index.mjs';
import { IBizReportPanelControl } from './control/report-panel/index.mjs';
import { IBizGanttControl } from './control/gantt/index.mjs';
import { IBizContextMenuControl } from './control/context-menu/index.mjs';
import { IBizViewPanelControl } from './control/view-panel/index.mjs';

"use strict";
var IBizVue3 = {
  install: (v) => {
    ibiz.i18n = iBizI18n;
    ibiz.util.getExcelUtil = () => import('./util/xlsx-util/xlsx-util.mjs');
    registerErrorViewProvider("404", () => ({ component: View404 }));
    registerErrorViewProvider("403", () => ({ component: View403 }));
    v.use(IBizCommonComponents);
    v.use(IBizPanelComponents);
    v.use(IBizViewEngine);
    v.use(IBizView);
    v.use(IBizPortalView);
    v.use(IBizHtmlView);
    v.use(IBizWFStepTraceView);
    v.use(IBizDeRedirectView);
    v.use(IBizSubAppRefView);
    v.use(IBizDataViewControl);
    v.use(IBizTreeControl);
    v.use(IBizAppMenuControl);
    v.use(IBizAppMenuIconViewControl);
    v.use(IBizGridControl);
    v.use(IBizTreeGridControl);
    v.use(IBizListControl);
    v.use(IBizChartControl);
    v.use(IBizPickupViewPanelControl);
    v.use(IBizToolbarControl);
    v.use(IBizViewLayoutPanelControl);
    v.use(IBizPanelControl);
    v.use(IBizFormControl);
    v.use(IBizListExpBarControl);
    v.use(IBizDataViewExpBarControl);
    v.use(IBizGridExpBarControl);
    v.use(IBizSearchFormControl);
    v.use(IBizEditFormControl);
    v.use(IBizCaptionBarControl);
    v.use(IBizTabExpPanelControl);
    v.use(IBizTreeExpBarControl);
    v.use(IBizSearchBarControl);
    v.use(IBizWizardPanelControl);
    v.use(IBizDRBarControl);
    v.use(IBizDRTabControl);
    v.use(IBizDashboardControl);
    v.use(IBizCalendarControl);
    v.use(IBizCalendarExpBarControl);
    v.use(IBizKanbanControl);
    v.use(IBizTreeGridExControl);
    v.use(IBizMEditViewPanelControl);
    v.use(IBizChartExpBarControl);
    v.use(IBizMapControl);
    v.use(IBizReportPanelControl);
    v.use(IBizGanttControl);
    v.use(IBizContextMenuControl);
    v.use(IBizViewPanelControl);
    v.use(IBizEditor);
    v.use(IBizDirectives);
  }
};

export { IBizVue3 as default };
