'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var vue3Util = require('@ibiz-template/vue3-util');
var index = require('./auth-userinfo/index.cjs');
var index$1 = require('./nav-pos-index/index.cjs');
var index$a = require('./nav-tabs/index.cjs');
var index$b = require('./nav-breadcrumb/index.cjs');
var index$2 = require('./panel-button/index.cjs');
var index$3 = require('./panel-app-title/index.cjs');
var index$c = require('./panel-app-header/index.cjs');
var index$d = require('./panel-view-header/index.cjs');
var index$e = require('./panel-exp-header/index.cjs');
var index$f = require('./panel-view-content/index.cjs');
var index$4 = require('./panel-tab-panel/index.cjs');
var index$5 = require('./split-container/index.cjs');
var index$6 = require('./panel-index-view-search/index.cjs');
var index$g = require('./panel-app-login-view/index.cjs');
var index$h = require('./panel-remember-me/index.cjs');
var index$7 = require('./index-actions/index.cjs');
var index$i = require('./user-message/index.cjs');
var index$j = require('./searchform-buttons/index.cjs');
var index$k = require('./view-message/index.cjs');
var index$l = require('./panel-static-carousel/index.cjs');
var index$m = require('./coop-pos/index.cjs');
var index$n = require('./view-msg-pos/index.cjs');
var index$8 = require('./user-action/index.cjs');
var index$o = require('./data-import/index.cjs');
var index$p = require('./short-cut/index.cjs');
var index$q = require('./auth-captcha/index.cjs');
var index$r = require('./panel-button-list/index.cjs');
var index$9 = require('./auth-sso/index.cjs');
var navPosIndex_state = require('./nav-pos-index/nav-pos-index.state.cjs');
var navPosIndex_controller = require('./nav-pos-index/nav-pos-index.controller.cjs');
var panelButton_controller = require('./panel-button/panel-button.controller.cjs');
var panelAppTitle_controller = require('./panel-app-title/panel-app-title.controller.cjs');
var splitContainer_controller = require('./split-container/split-container.controller.cjs');

"use strict";
const IBizPanelComponents = {
  install: (v) => {
    v.use(index$9.IBizAuthSso);
    v.use(vue3Util.IBizPanelCtrlViewPageCaption);
    v.use(vue3Util.IBizPanelContainer);
    v.use(vue3Util.IBizPanelCtrlPos);
    v.use(vue3Util.IBizScrollContainer);
    v.use(index.IBizAuthUserinfo);
    v.use(index$1.IBizNavPosIndex);
    v.use(index$a.IBizNavTabs);
    v.use(index$b.IBizNavBreadcrumb);
    v.use(index$2.IBizPanelButton);
    v.use(vue3Util.IBizNavPos);
    v.use(index$3.IBizPanelAppTitle);
    v.use(vue3Util.IBizSingleDataContainer);
    v.use(vue3Util.IBizMultiDataContainer);
    v.use(vue3Util.IBizMultiDataContainerRaw);
    v.use(vue3Util.IBizPanelField);
    v.use(index$c.IBizPanelAppHeader);
    v.use(index$d.IBizPanelViewHeader);
    v.use(index$e.IBizPanelExpHeader);
    v.use(vue3Util.IBizPanelRawItem);
    v.use(index$f.IBizPanelViewContent);
    v.use(vue3Util.IBizGridContainer);
    v.use(index$4.IBizPanelTabPanel);
    v.use(vue3Util.IBizPanelTabPage);
    v.use(index$5.IBizSplitContainer);
    v.use(index$6.IBizPanelIndexViewSearch);
    v.use(index$g.IBizPanelAppLoginView);
    v.use(index$h.IBizPanelRememberMe);
    v.use(index$7.IBizIndexActions);
    v.use(vue3Util.IBizPanelContainerGroup);
    v.use(index$i.IBizUserMessage);
    v.use(vue3Util.IBizPanelContainerImage);
    v.use(index$j.IBizSearchFormButtons);
    v.use(vue3Util.IBizPanelItemRender);
    v.use(index$k.IBizViewMessage);
    v.use(index$l.IBizPanelStaticCarousel);
    v.use(vue3Util.IBizTeleportPlaceholder);
    v.use(vue3Util.IBizPanelContainerTabs);
    v.use(index$m.IBizCoopPos);
    v.use(index$n.IBizViewMsgPos);
    v.use(index$8.IBizUserAction);
    v.use(index$o.IBizDataImport);
    v.use(index$p.IBizShortCut);
    v.use(index$q.IBizAuthCaptcha);
    v.use(index$r.IBizPanelButtonList);
    v.use(vue3Util.IBizAuthWxmpQrcode);
  }
};

exports.IBizAuthUserinfo = index.IBizAuthUserinfo;
exports.IBizNavPosIndex = index$1.IBizNavPosIndex;
exports.IBizPanelButton = index$2.IBizPanelButton;
exports.IBizPanelAppTitle = index$3.IBizPanelAppTitle;
exports.IBizPanelTabPanel = index$4.IBizPanelTabPanel;
exports.IBizSplitContainer = index$5.IBizSplitContainer;
exports.IBizPanelIndexViewSearch = index$6.IBizPanelIndexViewSearch;
exports.IBizIndexActions = index$7.IBizIndexActions;
exports.IBizUserAction = index$8.IBizUserAction;
exports.NavPosIndexState = navPosIndex_state.NavPosIndexState;
exports.NavPosIndexController = navPosIndex_controller.NavPosIndexController;
exports.PanelButtonController = panelButton_controller.PanelButtonController;
exports.PanelAppTitleController = panelAppTitle_controller.PanelAppTitleController;
exports.SplitContainerController = splitContainer_controller.SplitContainerController;
exports.IBizPanelComponents = IBizPanelComponents;
exports.default = IBizPanelComponents;
