import AppIndexViewLayout_NO_NAV from './app-index-view-layout-no-nav.mjs';
import AppIndexViewLayout_TOP_NO_NAV from './app-index-view-layout-top-nonav.mjs';
import AppIndexViewLayout_BLANK_MODE from './app-index-view-layout-blank-mode.mjs';
import AppIndexViewLayout_CENTER from './app-index-view-layout-center.mjs';
import AppIndexViewLayout_TOP from './app-index-view-layout-top.mjs';
import AppIndexViewLayout from './app-index-view-layout.mjs';
import AppLoginView from './app-login-view.mjs';
import AppDataUploadView from './app-data-upload-view.mjs';
import AppStartViewLayout from './app-start-view-layout.mjs';
import AppWelComeViewLayout from './app-welcome-view-layout.mjs';
import DEChartView from './view-layout-model-repository/view-layout-model-repository-de-chart-view-layout.mjs';
import DECalendarExpView from './view-layout-model-repository/view-layout-model-repository-de-calendar-exp-view-layout.mjs';
import DECalendarView from './view-layout-model-repository/view-layout-model-repository-de-calendar-view-layout.mjs';
import DEDataViewExpView from './view-layout-model-repository/view-layout-model-repository-de-data-view-exp-view-layout.mjs';
import DEDataView from './view-layout-model-repository/view-layout-model-repository-de-data-view-layout.mjs';
import DEKanbanView from './view-layout-model-repository/view-layout-model-repository-de-kanban-view-layout.mjs';
import DEEdit2View from './view-layout-model-repository/view-layout-model-repository-de-edit-view-2-layout.mjs';
import DEEdit3View from './view-layout-model-repository/view-layout-model-repository-de-edit-view-3-layout.mjs';
import DEEdit4View from './view-layout-model-repository/view-layout-model-repository-de-edit-view-4-layout.mjs';
import DEFormPickupDataView from './view-layout-model-repository/view-layout-model-repository-form-pickup-data-view.mjs';
import DEEditView from './view-layout-model-repository/view-layout-model-repository-de-edit-view-layout.mjs';
import DEGridViewExpView from './view-layout-model-repository/view-layout-model-repository-de-grid-exp-view-layout.mjs';
import DEGridView from './view-layout-model-repository/view-layout-model-repository-de-grid-view-layout.mjs';
import DEListViewExpView from './view-layout-model-repository/view-layout-model-repository-de-list-exp-view-layout.mjs';
import DEListView from './view-layout-model-repository/view-layout-model-repository-de-list-view-layout.mjs';
import DEOptView from './view-layout-model-repository/view-layout-model-repository-de-option-view-layout.mjs';
import DEPickupGirdView from './view-layout-model-repository/view-layout-model-repository-de-pickup-grid-view-layout.mjs';
import DEPickupTreeView from './view-layout-model-repository/view-layout-model-repository-de-pickup-tree-view-layout.mjs';
import DEPickupView2 from './view-layout-model-repository/view-layout-model-repository-de-pickup-view-2-layout.mjs';
import DEPickupView from './view-layout-model-repository/view-layout-model-repository-de-pickup-view-layout.mjs';
import DETabExpView from './view-layout-model-repository/view-layout-model-repository-de-tab-exp-view-layout.mjs';
import DETreeViewExpView from './view-layout-model-repository/view-layout-model-repository-de-tree-exp-view-layout.mjs';
import DETreeView from './view-layout-model-repository/view-layout-model-repository-de-tree-view-layout.mjs';
import DEWizardDView from './view-layout-model-repository/view-layout-model-repository-de-wizard-view-layout.mjs';
import DEMPickupView from './view-layout-model-repository/view-layout-model-repository-dem-pickup-view-layout.mjs';
import DEMPickupView2 from './view-layout-model-repository/view-layout-model-repository-dem-pickup-view-2-layout.mjs';
import DEWFDynaActionView from './view-layout-model-repository/view-layout-model-repository-dewf-dyna-action-view-layout.mjs';
import DEWFDynaStartView from './view-layout-model-repository/view-layout-model-repository-dewf-dyna-start-view-layout.mjs';
import DEWFDynaEditView3 from './view-layout-model-repository/view-layout-model-repository-dewf-dyna-edit-view-3-layout.mjs';
import DEWFDynaEditView from './view-layout-model-repository/view-layout-model-repository-dewf-dyna-edit-view-layout.mjs';
import DEPanelView from './view-layout-model-repository/view-layout-model-repository-de-panel-view-layout.mjs';
import DEPickupDataView from './view-layout-model-repository/view-layout-model-repository-de-pickup-data-view-layout.mjs';
import DEIndexPickupDataView from './view-layout-model-repository/view-layout-model-repository-de-index-pickup-data-view-layout.mjs';
import DETreeGridExView from './view-layout-model-repository/view-layout-model-repository-de-tree-grid-ex-view-layout.mjs';
import DETreeGridView from './view-layout-model-repository/view-layout-model-repository-de-tree-grid-view-layout.mjs';
import DEMEditView9 from './view-layout-model-repository/view-layout-model-repository-dem-edit-view-9-layout.mjs';
import DEChartExpView from './view-layout-model-repository/view-layout-model-repository-de-chart-exp-view-layout.mjs';
import DEMAPVIEW from './view-layout-model-repository/view-layout-model-repository-de-map-view-layout.mjs';
import DEREPORTVIEW from './view-layout-model-repository/view-layout-model-repository-de-report-view-layout.mjs';
import DEGANTTVIEW from './view-layout-model-repository/view-layout-model-repository-de-gantt-view-layout.mjs';
import DEINDEXVIEW from './view-layout-model-repository/view-layout-model-repository-de-index-view-layout.mjs';
import DETABSEARCHVIEW from './view-layout-model-repository/view-layout-model-repository-de-tab-search-view-view-layout.mjs';
import DETABEXPVIEW_FLOW from './view-layout-model-repository/view-layout-model-repository-de-tab-exp-view-layout-flow.mjs';
import DEMEDITVIEW9_TOP from './view-layout-model-repository/view-layout-model-repository-dem-edit-view-9-layout-top.mjs';
import AppPanelView from './view-layout-model-repository/view-layout-model-repository-app-panel-view-layout.mjs';
import GridExpBar from './control-layout/control-layout-model-repository-grid-exp-bar-layout.mjs';
import ListExpBar from './control-layout/control-layout-model-repository-list-exp-bar-layout.mjs';
import DataViewExpBar from './control-layout/control-layout-model-repository-data-view-exp-bar-layout.mjs';
import TreeExpBar from './control-layout/control-layout-model-repository-tree-exp-bar-layout.mjs';
import ChartExpBar from './control-layout/control-layout-model-repository-chart-exp-bar-layout.mjs';
import SearchForm from './control-layout/control-layout-model-repository-search-form-layout.mjs';
import Tree from './control-layout/control-layout-model-repository-tree-layout.mjs';
import DataView from './control-layout/control-layout-model-repository-data-view-layout.mjs';
import CalendarExpBar from './control-layout/control-layout-model-repository-calendar-exp-bar-layout.mjs';

"use strict";
function install(callBack) {
  callBack("APPINDEXVIEW_DEFAULT", AppIndexViewLayout);
  callBack("APPINDEXVIEW_DEFAULT_LEFT", AppIndexViewLayout);
  callBack("APPINDEXVIEW_DEFAULT_BLANK_MODE", AppIndexViewLayout_BLANK_MODE);
  callBack("APPINDEXVIEW_DEFAULT_CENTER", AppIndexViewLayout_CENTER);
  callBack("APPINDEXVIEW_DEFAULT_TOP", AppIndexViewLayout_TOP);
  callBack("APPINDEXVIEW_DEFAULT_NO_NAV", AppIndexViewLayout_NO_NAV);
  callBack("APPINDEXVIEW_DEFAULT_LEFT_NO_NAV", AppIndexViewLayout_NO_NAV);
  callBack("APPINDEXVIEW_DEFAULT_TOP_NO_NAV", AppIndexViewLayout_TOP_NO_NAV);
  callBack("APPLOGINVIEW_DEFAULT", AppLoginView);
  callBack("APPDATAUPLOADVIEW_DEFAULT", AppDataUploadView);
  callBack("APPSTARTVIEW_DEFAULT", AppStartViewLayout);
  callBack("APPWELCOMEVIEW_DEFAULT", AppWelComeViewLayout);
  callBack("DECHARTVIEW_DEFAULT", DEChartView);
  callBack("DECHARTVIEW9_DEFAULT", DEChartView);
  callBack("DECALENDAREXPVIEW_DEFAULT", DECalendarExpView);
  callBack("DECALENDARVIEW_DEFAULT", DECalendarView);
  callBack("DECALENDARVIEW9_DEFAULT", DECalendarView);
  callBack("DEDATAVIEWEXPVIEW_DEFAULT", DEDataViewExpView);
  callBack("DEDATAVIEW_DEFAULT", DEDataView);
  callBack("DEDATAVIEW9_DEFAULT", DEDataView);
  callBack("DEKANBANVIEW_DEFAULT", DEKanbanView);
  callBack("DEEDITVIEW2_DEFAULT", DEEdit2View);
  callBack("DEEDITVIEW3_DEFAULT", DEEdit3View);
  callBack("DEEDITVIEW4_DEFAULT", DEEdit4View);
  callBack("DEFORMPICKUPDATAVIEW_DEFAULT", DEFormPickupDataView);
  callBack("DEEDITVIEW_DEFAULT", DEEditView);
  callBack("DEEDITVIEW9_DEFAULT", DEEditView);
  callBack("DEGRIDEXPVIEW_DEFAULT", DEGridViewExpView);
  callBack("DEGRIDVIEW_DEFAULT", DEGridView);
  callBack("DEGRIDVIEW9_DEFAULT", DEGridView);
  callBack("DELISTEXPVIEW_DEFAULT", DEListViewExpView);
  callBack("DELISTVIEW_DEFAULT", DEListView);
  callBack("DELISTVIEW9_DEFAULT", DEListView);
  callBack("DEOPTVIEW_DEFAULT", DEOptView);
  callBack("DEPICKUPGRIDVIEW_DEFAULT", DEPickupGirdView);
  callBack("DEPICKUPTREEVIEW_DEFAULT", DEPickupTreeView);
  callBack("DEPICKUPVIEW2_DEFAULT", DEPickupView2);
  callBack("DEPICKUPVIEW_DEFAULT", DEPickupView);
  callBack("DETABEXPVIEW_DEFAULT", DETabExpView);
  callBack("DETABEXPVIEW9_DEFAULT", DETabExpView);
  callBack("DETREEEXPVIEW_DEFAULT", DETreeViewExpView);
  callBack("DETREEVIEW_DEFAULT", DETreeView);
  callBack("DETREEVIEW9_DEFAULT", DETreeView);
  callBack("DEWIZARDVIEW_DEFAULT", DEWizardDView);
  callBack("DEMPICKUPVIEW_DEFAULT", DEMPickupView);
  callBack("DEMPICKUPVIEW2_DEFAULT", DEMPickupView2);
  callBack("DEWFDYNAACTIONVIEW_DEFAULT", DEWFDynaActionView);
  callBack("DEWFDYNASTARTVIEW_DEFAULT", DEWFDynaStartView);
  callBack("DEWFDYNAEDITVIEW3_DEFAULT", DEWFDynaEditView3);
  callBack("DEWFDYNAEDITVIEW_DEFAULT", DEWFDynaEditView);
  callBack("DEPANELVIEW_DEFAULT", DEPanelView);
  callBack("DEPICKUPDATAVIEW_DEFAULT", DEPickupDataView);
  callBack("DEINDEXPICKUPDATAVIEW_DEFAULT", DEIndexPickupDataView);
  callBack("DETREEGRIDEXVIEW_DEFAULT", DETreeGridExView);
  callBack("DETREEGRIDVIEW_DEFAULT", DETreeGridView);
  callBack("DEMEDITVIEW9_DEFAULT", DEMEditView9);
  callBack("DECHARTEXPVIEW_DEFAULT", DEChartExpView);
  callBack("DEMAPVIEW_DEFAULT", DEMAPVIEW);
  callBack("DEREPORTVIEW_DEFAULT", DEREPORTVIEW);
  callBack("DEGANTTVIEW_DEFAULT", DEGANTTVIEW);
  callBack("DEINDEXVIEW_DEFAULT", DEINDEXVIEW);
  callBack("DETABSEARCHVIEW_DEFAULT", DETABSEARCHVIEW);
  callBack("DETABEXPVIEW_FLOW", DETABEXPVIEW_FLOW);
  callBack("DEMEDITVIEW9_TOP", DEMEDITVIEW9_TOP);
  callBack("GRIDEXPBAR_DEFAULT", GridExpBar);
  callBack("LISTEXPBAR_DEFAULT", ListExpBar);
  callBack("DATAVIEWEXPBAR_DEFAULT", DataViewExpBar);
  callBack("TREEEXPBAR_DEFAULT", TreeExpBar);
  callBack("CHARTEXPBAR_DEFAULT", ChartExpBar);
  callBack("SEARCHFORM_DEFAULT", SearchForm);
  callBack("TREEVIEW_DEFAULT", Tree);
  callBack("DATAVIEW_DEFAULT", DataView);
  callBack("CALENDAREXPBAR_DEFAULT", CalendarExpBar);
  callBack("APPPANELVIEW_DEFAULT", AppPanelView);
}

export { install };
